### ISSUE TITLE
[Vue warn]:  Computed property "currentLabel" was assigned to but it has no setter

### ISSUE THREAD

**Issue by slimtom95** [kooriookami/el-select-v2#1]
This warning seems not affect the client function at all, but it would be better if we can eliminate it.

Thrown from this line:

![image](https://github.com/kooriookami/el-select-v2/assets/20624187/2a3f351c-d24b-451d-8070-acf02e91291f)

ElOption source codes link:
https://github.com/ElemeFE/element/blob/dev/packages/select/src/option.vue

![image](https://github.com/kooriookami/el-select-v2/assets/20624187/f6053f3c-9545-4a9d-9e9d-49d9ba00caf0)

**Comment by kooriookami** [comment]
I found the reason not the computed `currentLabel` but the instance of `Option` component.
Line 147 pushes a `this`, it's not a pure object, so it cann't set the currentLabel.
https://github.com/ElemeFE/element/blob/dev/packages/select/src/option.vue#L147
![image](https://github.com/kooriookami/el-select-v2/assets/38392315/f5430c41-d480-4561-800d-a95106eefaf2)

**Comment by kooriookami** [comment]
Fixed and close.
