### ISSUE TITLE
v-model绑定的值更新，且不在下拉列表中，点击下拉框时，不显示无数据，但也没有匹配项

### ISSUE THREAD

**Issue by cug-zgj** [kooriookami/el-select-v2#10]

**Comment by kooriookami** [comment]
有demo吗，如果绑定一个不匹配的值，输入框会显示绑定的value，这是正常的

**Comment by cug-zgj** [comment]
输入框显示绑定的value是没问题的，就是下拉列表没有匹配项没提示，像是原生的el-select有这个处理，更新v-model的值，会是下面这个效果。
![image](https://github.com/kooriookami/el-select-v2/assets/20136274/9886d142-a6c0-49b9-92e1-d4ed56846756)

**Comment by kooriookami** [comment]
我昨天试了下，修改不同的绑定值，不会影响下拉列表的选项。你这个是怎么操作的

**Comment by yusgboy** [comment]
> 输入框显示绑定的value是没问题的，就是下拉列表没有匹配项没提示，像是原生的el-select有这个处理，更新v-model的值，会是下面这个效果。 ![image](https://private-user-images.githubusercontent.com/20136274/336265828-9886d142-a6c0-49b9-92e1-d4ed56846756.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1ODU0MzMsIm5iZiI6MTcxODU4NTEzMywicGF0aCI6Ii8yMDEzNjI3NC8zMzYyNjU4MjgtOTg4NmQxNDItYTZjMC00OWI5LTkyZTEtZDRlZDU2ODQ2NzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDAwNDUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzOTdlNjE5YTgyNGQxYzc1ZTE5ZDhmOTA3YTlmYmI4MjY3N2M1NWRlNjMyZjA2NzA4YzdkZjMxMmU0NDAzY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.emDkJ_iwirrcyfdijA42Z9umA1WeMxqCkT7o-YGsv4M)

你是指远程搜索后选中一个值，然后可能保存了，然后回显的时候初始的option因为实际没有这个值option，然后就显示你这种情况了吧
