### ISSUE TITLE
下拉列表存在空行，可能是translateY计算错误了

### ISSUE THREAD

**Issue by czh1998yr** [kooriookami/el-select-v2#11]
下拉列表存在空行，可能是translateY计算错误了
![微信截图_20240605104107](https://github.com/kooriookami/el-select-v2/assets/80443179/83d06642-75af-4f28-8610-29f4688bc006)

**Comment by czh1998yr** [comment]
![微信截图_20240605104457](https://github.com/kooriookami/el-select-v2/assets/80443179/deed09d8-2423-41b5-8795-4bc10d6fdba3)

**Comment by czh1998yr** [comment]
![2](https://github.com/kooriookami/el-select-v2/assets/80443179/dc5cecf9-6d9a-4056-b6ba-6539bc091a79)
![3](https://github.com/kooriookami/el-select-v2/assets/80443179/bb472143-6944-4a96-959b-f9b9b4eb1e8f)
现象还不太一致，有时候直接没有这个dom元素

**Comment by kooriookami** [comment]
有可复现的demo吗

**Comment by czh1998yr** [comment]
![1](https://github.com/kooriookami/el-select-v2/assets/80443179/1164391d-c7f5-409c-9fcb-171f9f7a39e3)
![2](https://github.com/kooriookami/el-select-v2/assets/80443179/0610afd5-5741-4ecd-b82e-bc25fb989e2a)
![3](https://github.com/kooriookami/el-select-v2/assets/80443179/54ab5e26-0704-416e-b791-c907d6c33798)
问题的原因是因为存在两个相同的value，由于我这个数据比较特殊，在这个业务场景中，我的value并不一定是唯一值

**Comment by kooriookami** [comment]
那这个不属于正常使用的范围内，不属于组件的问题。value重复空白的特性是vue-virtual-scroller导致的。

**Comment by czh1998yr** [comment]
好的，感谢，我注意到在您封装的组件中是以 value 作为 RecycleScroller 的 keyField，我通过将您设置的 keyField 去除，使用默认值 id，并在传输 options 到组件时，重新构建数据，动态生成 id 解决了这个问题
