### ISSUE TITLE
可以增加一个全选的功能么，类似element-plus里的自定义头部

### ISSUE THREAD

**Issue by cug-zgj** [kooriookami/el-select-v2#17]

**Comment by kooriookami** [comment]
可以添加两个插槽，一会我看看

**Comment by kooriookami** [comment]
el-select内部用cachedOption缓存了label信息，每次选择会刷新cachedOption，如果有上万个数据操作会卡，我没想到什么好的办法。

**Comment by cug-zgj** [comment]
cachedOption缓存的不是可见的部分么，那应该没多大啊，不知道是我理解的有问题么

**Comment by kooriookami** [comment]
缓存的是选中的选项，不然label就展示不了了

**Comment by cug-zgj** [comment]
element-plus的el-select-v2的5w条数据的全选没有这种卡顿的现象，不知道可不可以参考，还是说vue2的el-select-v2是对el-select的二次封装，全选这种的操作调用本身的接口实现效果就是不太好，除非重新实现一个

**Comment by kooriookami** [comment]
是二次封装的，所以魔改程度有限

**Comment by cug-zgj** [comment]
如果有这种全选，量大的需求，目前是不是没什么好办法，只能转战element-plus了....




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月24日(星期二) 下午5:46
收件人: ***@***.***&gt;; 
抄送: "Unlimited Blade ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kooriookami/el-select-v2] 可以增加一个全选的功能么，类似element-plus里的自定义头部 (Issue #17)















是二次封装的，所以魔改程度有限

**Comment by kooriookami** [comment]
是的，或者找别的组件库替代了

**Comment by cug-zgj** [comment]
你好，我看了下element-ui的源码，感觉全选更新label，主要就耗时在这个getOption了，这个函数里会for循环在cachedOptions里查找，假如我改下他的源码，把这个cachedOptions用map替代，能把查找的复杂度从O(n)降到O(1)，这么做是不是可行

**Comment by cug-zgj** [comment]
然后魔改下您的代码

**Comment by kooriookami** [comment]
可以试试哈
