### ISSUE TITLE
在  change 事件中，尝试将绑定的值清空时，触发了清空逻辑，但选中项的值并未被清空，依旧显示选中的值

### ISSUE THREAD

**Issue by mietl** [kooriookami/el-select-v2#18]
### 检查清单

- [X] 我已确认当前的 issues 列表中并未有人提出过相同的问题
- [X] 我已确认仓库的 PR 列表中并未有解决该问题的 PR

### 问题描述

在  change 事件中，尝试将绑定的值清空时，触发了清空逻辑，但选中项的值并未被清空，依旧显示选中的值

### 复现步骤

1. 打开下方最小复现中的 el-select-v2/src/components/Demo.vue 文件
2. 选择下拉框中的某个项目
3. 在 change 事件中尝试清空绑定的值
4. 观察到选择的值没有被清空，仍然显示的是之前选中的项

### 预期行为
在 change 事件中成功清空绑定的值，清空后应当没有选中项，显示为空。

### 最小复现 
[el-select-v2.zip](https://github.com/user-attachments/files/17106332/el-select-v2.zip)
文件中包含测试 使用 el-select 不会有该问题

### 系统信息

 System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M2
    Memory: 90.56 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - /usr/local/bin/node
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 9.9.0 - ~/Library/pnpm/pnpm
    bun: 1.1.25 - ~/.bun/bin/bun
  Browsers:
    Chrome: 128.0.6613.120
    Safari: 18.0

**Comment by kooriookami** [comment]
你的demo中$nextTick是可以解决的，只是你把value1和value2写反了。

**Comment by mietl** [comment]
> 你的demo中$nextTick是可以解决的，只是你把value1和value2写反了。

不好意思，实际应用中我遇到了问题，使用 $nextTick 也没能解决。但在写复现代码的时候，不清醒没写对，以为复现了

刚刚听你这么一说，我又去找原因了，发现其实是其他原因导致的， 问题已经解决了。

打扰了。

**Comment by mietl** [comment]
支持支持🧡
