### ISSUE TITLE
通过键盘导航

### ISSUE THREAD

**Issue by hongkb24** [kooriookami/el-select-v2#2]
想法是通过键盘38 40改变可视数据列表,这个需求有实现思路吗?

**Comment by kooriookami** [comment]
没听明白，按Tab键导航吗

**Comment by hongkb24** [comment]
@kooriookami https://element-plus.gitee.io/zh-CN/component/select-v2.html ,element-plus的select-v2,input聚焦后可以使用上下键滚动数据(可以看作改变可视窗口的数据)

**Comment by hongkb24** [comment]
![Untitled ‑ Made with FlexClip](https://github.com/kooriookami/el-select-v2/assets/78244354/8ff9a7d3-81fe-4c01-bcf3-a94b4c0f588e)

**Comment by kooriookami** [comment]
我知道了，这个后面可以加。你可以先看看ep源码的实现。

**Comment by kooriookami** [comment]
1.4.2版本添加
