### ISSUE TITLE
可以增加树形接口数据功能吗？

### ISSUE THREAD

**Issue by amen943** [kooriookami/el-select-v2#20]
RT,谢谢

**Comment by kooriookami** [comment]
树形选择有单独的组件：https://github.com/yujinpan/el-select-tree

**Comment by amen943** [comment]
> 树形选择有单独的组件：https://github.com/yujinpan/el-select-tree

它这个有bug ...

**Comment by kooriookami** [comment]
那给它提issue，树形组件比这个组件更复杂
