### ISSUE TITLE
popper-class不生效

### ISSUE THREAD

**Issue by CirillaQL** [kooriookami/el-select-v2#21]
我目前在一个Vue2项目中尝试使用el-select-v2，按照下图的参数设置后：
![微信截图_20241028143555](https://github.com/user-attachments/assets/bd9196ed-ffa4-403d-8e2b-7b196e5580de)
![微信截图_20241028143432](https://github.com/user-attachments/assets/3af2e5e6-6268-4325-b16f-4871869e9ded)
显示情况是：
![微信截图_20241028143606](https://github.com/user-attachments/assets/0ba7e406-4778-418d-bac3-93b0c6f9c329)
下拉菜单的item的height仍然为34
![微信截图_20241028143409](https://github.com/user-attachments/assets/ba4644df-bedb-4b38-b045-993e8adc809e)
使用item-height同样不生效，
之前使用element-ui的el-select时，同样的配置可以正常使用。
不是专业前端开发人员，所以不确定问题在哪里。

**Comment by kooriookami** [comment]
有个min-item-size也需要设置一下，修改成你需要的高度。

**Comment by CirillaQL** [comment]
> 有个min-item-size也需要设置一下，修改成你需要的高度。

谢谢，修改了一下好了些。
