### ISSUE TITLE
开启 filterable 与 allow-create 后 产生的新选项会在 #header 插槽之上

### ISSUE THREAD

**Issue by mietl** [kooriookami/el-select-v2#22]
### 检查清单

- [X] 我已确认当前的 issues 列表中并未有人提出过相同的问题
- [X] 我已确认仓库的 PR 列表中并未有解决该问题的 PR

### 问题描述

开启 el-select-v2 使用 filterable 与 allow-create 产生的新选项会在 #header 插槽之上

<img width="478" alt="image" src="https://github.com/user-attachments/assets/633d7e5b-08b5-4a0c-af50-afa3c7bae41a">

### 复现步骤

1. 将 filterable 设置为 true 并且 允许用户创建新条目(allow-create)
2. 当绑定的值不存在下拉列表中时，产生新选项，问题浮现了，产生的新选项处于 #header 插槽之上

### 预期行为
在#header插槽位置之下

### 最小复现 
[el-select-v2.zip](https://github.com/user-attachments/files/17685640/el-select-v2.zip)

打开下方最小复现中的 el-select-v2/src/components/Demo.vue 文件

这次我很清醒

**Comment by kooriookami** [comment]
![01505050](https://github.com/user-attachments/assets/1e6994eb-c629-4dfb-b77b-28c2f1c310fe)
好像不好改了

**Comment by mietl** [comment]
> ![01505050](https://private-user-images.githubusercontent.com/38392315/384585030-1e6994eb-c629-4dfb-b77b-28c2f1c310fe.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDg5ODYsIm5iZiI6MTczMTI0ODY4NiwicGF0aCI6Ii8zODM5MjMxNS8zODQ1ODUwMzAtMWU2OTk0ZWItYzYyOS00ZGZiLWI3N2ItMjhjMmYxYzMxMGZlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDE0MjQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlN2M1NTVkNWMzNzU4NTMwZjdjZDVmMzU4YmVkZTMwYjljZDRjZDQ5N2UzNDYyMmJjNjJjYzI5M2I4ODc2M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VJ0vcP9WRqyjL3CcI9uE2sakc2EiFRzBSD_jIJPnDT4) [ ![01505050](https://private-user-images.githubusercontent.com/38392315/384585030-1e6994eb-c629-4dfb-b77b-28c2f1c310fe.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDg5ODYsIm5iZiI6MTczMTI0ODY4NiwicGF0aCI6Ii8zODM5MjMxNS8zODQ1ODUwMzAtMWU2OTk0ZWItYzYyOS00ZGZiLWI3N2ItMjhjMmYxYzMxMGZlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDE0MjQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlN2M1NTVkNWMzNzU4NTMwZjdjZDVmMzU4YmVkZTMwYjljZDRjZDQ5N2UzNDYyMmJjNjJjYzI5M2I4ODc2M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VJ0vcP9WRqyjL3CcI9uE2sakc2EiFRzBSD_jIJPnDT4) ](https://private-user-images.githubusercontent.com/38392315/384585030-1e6994eb-c629-4dfb-b77b-28c2f1c310fe.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDg5ODYsIm5iZiI6MTczMTI0ODY4NiwicGF0aCI6Ii8zODM5MjMxNS8zODQ1ODUwMzAtMWU2OTk0ZWItYzYyOS00ZGZiLWI3N2ItMjhjMmYxYzMxMGZlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDE0MjQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlN2M1NTVkNWMzNzU4NTMwZjdjZDVmMzU4YmVkZTMwYjljZDRjZDQ5N2UzNDYyMmJjNjJjYzI5M2I4ODc2M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VJ0vcP9WRqyjL3CcI9uE2sakc2EiFRzBSD_jIJPnDT4) [ ](https://private-user-images.githubusercontent.com/38392315/384585030-1e6994eb-c629-4dfb-b77b-28c2f1c310fe.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDg5ODYsIm5iZiI6MTczMTI0ODY4NiwicGF0aCI6Ii8zODM5MjMxNS8zODQ1ODUwMzAtMWU2OTk0ZWItYzYyOS00ZGZiLWI3N2ItMjhjMmYxYzMxMGZlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDE0MjQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlN2M1NTVkNWMzNzU4NTMwZjdjZDVmMzU4YmVkZTMwYjljZDRjZDQ5N2UzNDYyMmJjNjJjYzI5M2I4ODc2M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VJ0vcP9WRqyjL3CcI9uE2sakc2EiFRzBSD_jIJPnDT4) 好像不好改了

是哦 el-select 源码里 `<el-option
            :value="query"
            created
            v-if="showNewOption">
          </el-option>
           <slot></slot> ` 他产生的option在插槽前面😭

**Comment by kooriookami** [comment]
在1.4.0版本中修复
