### ISSUE TITLE
文档中写的options的value 支持 object 类型，但使用时提示警告

### ISSUE THREAD

**Issue by ddztomcat** [kooriookami/el-select-v2#23]
el-select的value-key与el-select-v2的value-key 含义不一样

**Comment by kooriookami** [comment]
这个和element-plus的el-select-v2的value-key是一致的，对象里的value-key之后可以优化一下，会和element-plus同步用法。

**Comment by kooriookami** [comment]
1.4.0版本支持使用 object-key 绑定对象值
