### ISSUE TITLE
下拉显示文字过多时显示不全

### ISSUE THREAD

**Issue by hongpy** [kooriookami/el-select-v2#3]
![宽度显示不全](https://github.com/kooriookami/el-select-v2/assets/24297048/d6c832a3-0f59-48a1-aa22-58bd870f4cf9)

应该如何设置

**Comment by kooriookami** [comment]
虚拟滚动没有办法自适应宽度，可以使用样式覆盖 `.el-select-v2__popper` 的宽度。

**Comment by kooriookami** [comment]
更新到1.1.0版本，设置fit-input-width为false可以自动计算宽度
