### ISSUE TITLE
可搜索时，输入关键字，选中后，再次点击弹出下拉后，下拉框只包含根据该关键字搜索的内容，而不是全部下拉项

### ISSUE THREAD

**Issue by cug-zgj** [kooriookami/el-select-v2#6]
![image](https://github.com/kooriookami/el-select-v2/assets/20136274/5cbaaf58-a77e-4062-8a36-8bea5b186cc4)
失焦后恢复正常

**Comment by cug-zgj** [comment]
我学习了下代码，监听下拉框出现事件时更新localOptions就可以了，去掉之前的focus事件监听。猜测是选中后什么都不做，直接再点下拉框，没触发focus事件，导致localOptions没更新，不知道这么做可以么

**Comment by kooriookami** [comment]
确实，我发布了 1.0.7 版本修复了此问题 :D
